### PR TITLE
Alternate promisification using promise-shim

### PR DESCRIPTION
**Pull request by jamestalmage**
If we move the callback to the first argument it gets easy to implement promisification using `promise-shim`.

So easy it might be better to not return promises and either:

 1. show the user how to promisify it themselves
 2. deploy a separate module that wraps this one and promisifies it.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hey, sorry about the delay. I had some other stuff on my plate and I was not convinced with this solution, but didn't have something better.

I feel having the callback as the first argument is kind of strange.

Would it be simpler if we check the presence of a global Promise object and only return it if it is present?

**Comment by jamestalmage** [comment]
> I feel having the callback as the first argument is kind of strange.

It is

>  I was not convinced with this solution

I'm not either

> Would it be simpler if we check the presence of a global Promise object and only return it if it is present

I am fine with detecting global as the default option, but we should provide a mechanism to set their own. `bluebird` in particular has a massive API that goes way beyond the base spec. We don't want to force people to take on that big dependency, but at the same time we do want to give them the ability to use that massive api if that is what they want. We also shouldn't demand that they overwrite global variables to change the promise implementation. We could just provide this:

```js
runAsync.setPromiseImplementation(require('bluebird'))
```

90% of users wouldn't ever touch this (they would just use native or global).

---------

The second problem is coming up with a clean API in the case where they don't have a callback, and just want us to provide a promise. A review of our options:

1.  `runAsync(fn, callback, ...rest)` becomes `runAsync(fn, null, ...rest).then` when you just want to use the promise. That's not pretty, but it is easy to implement and backwards compatible. If they aren't providing extra args, then `runAsync(fn).then` still looks pretty.

2. `runAsync(callback, fn, ...rest)` becomes `runAsync(null, fn, ...rest).then`. That easily becomes `runAsync(fn, ...rest).then` using `bind`. To me, this is the cleanest way, but it  breaks backwards compatibility in a very confusing way, and I am hesitant to pull the trigger on it for that reason alone. 

3. `runAsync(fn, callback)(rest)` becomes `runAsync(fn)(rest).then`. This is pretty slick, and I think potentially pretty convenient. It's essentially built in currying. However, it also breaks backwards compatibility in a very confusing way.

At this point I am leaning towards **1**, despite being not the prettiest in some cases. Both the other options are very bad breaking changes that will affect 100% of current users. With either **2** or **3** it would be impossible for us to detect that people are using it the old way and give them a helpful error message.

**Comment by SBoudrias** [comment]
I'm okay with the 3rd option. Only three public modules depends on run-async (2 who're mostly maintained by me).

We'll just bump a major version and people won't be affected unless they update. Also, the update path is fairly simple, things are not moving around in a very weird way.

Also, having `runAsync()` returning a function will probably make it easier to use in a lot of cases.

**Comment by jamestalmage** [comment]
closing in favor of #10

**Pull request closed without merging**
